serverUrl: http://localhost:8080/hmonws
analogBoard:
    spiAddress: 1
    spiName: analog
    channels:
      - mode: thermistor
        channel: 0
        name: Apartment 1 return
        beta: 3380
        inputReference: 10000
        inputRange: 4096
        notes: |
          Apartment 1 return uses a widgetlords thermistor
          Orange pair
      - mode: thermistor
        channel: 1
        name: Apartment 2 return
        beta: 3950
        inputReference: 10000
        inputRange: 4096
        notes: |
          Apartment 2 return uses an adafruit thermistor
          https://www.adafruit.com/product/372
          Blue pair
      - mode: thermistor
        channel: 2
        name: Boiler out
        beta: 3950
        inputReference: 10000
        inputRange: 4096
        notes: |
          Boiler out uses an adafruit thermistor
          https://www.adafruit.com/product/372
          Green pair

digitalBoards:
  - spiAddress: 3
    spiName: digital
    hardwareAddress: 0
    inputs:
      - index: 0
        name: "Apt #1 Bed/Bath"
        highTrue: true
        subZone: true
        zone: "Apartment 1"
      - index: 1
        name: "Apt #1 Back"
        highTrue: true
        subZone: true
        zone: "Apartment 1"
      - index: 2
        name: "Apt #1 Front"
        highTrue: true
        subZone: true
        zone: "Apartment 1"
      - index: 3
        name: "Apt #1 Kitchen"
        subZone: true
        highTrue: true
        zone: "Apartment 1"
  - spiAddress: 3
    spiName: digital
    hardwareAddress: 1
    inputs:
      - index: 0
        name: "24v Apartment 1"
        highTrue: true
        alwaysOn: true
      - index: 1
        name: "Apt #1 zone"
        highTrue: true
        zone: "Apartment 1"
        circulator: true
      - index: 2
        name: "Apt #2 zone"
        highTrue: true
        zone: "Apartment 2"
        circulator: true
      - index: 3
        name: "Water heater"
        highTrue: true
        zone: "Hot Water"
        circulator: true
